name: siembra_facil
description: "Aplicación para análisis inteligente de suelo agrícola"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  firebase_database: ^12.0.0
  intl: ^0.20.2
  http: ^1.1.0
  fl_chart: ^0.68.0
  firebase_ai: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
